version: '3.8'

services:
  backend:
    build: .
    container_name: daharmeet-backend
    image: daharmeet-backend:latest
    ports:
      - "3001:3001"
    restart: always
    environment:
      - PORT=3001
      - POCKETBASE_URL=${POCKETBASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
